/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_ai_recast_structures_BoundedField */

#ifndef _Included_com_jme3_ai_recast_structures_BoundedField
#define _Included_com_jme3_ai_recast_structures_BoundedField
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_ai_recast_structures_BoundedField
 * Method:    getNativeMaxBound
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jme3_ai_recast_structures_BoundedField_getNativeMaxBound
  (JNIEnv *, jobject);

/*
 * Class:     com_jme3_ai_recast_structures_BoundedField
 * Method:    getNativeMinBound
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jme3_ai_recast_structures_BoundedField_getNativeMinBound
  (JNIEnv *, jobject);

/*
 * Class:     com_jme3_ai_recast_structures_BoundedField
 * Method:    getNativeCellHeight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jme3_ai_recast_structures_BoundedField_getNativeCellHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_jme3_ai_recast_structures_BoundedField
 * Method:    getNativeCellSize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jme3_ai_recast_structures_BoundedField_getNativeCellSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
